### ISSUE TITLE
Support for USART full duplex

### ISSUE THREAD

**Issue by heyitscassio** [Bastardkb/adapter-blackpill#18]
QMK supports USART full duplex for arm based boards. 

It's what the cantor keyboard uses. The advantage is that it doesn't need pullup resistors. The disadvantage is that it will make necessary a TRRS cable, just a TRS cable would not be sufficient, and it would make the building process more confusing, in a way.

https://github.com/qmk/qmk_firmware/blob/master/docs/serial_driver.md#usart-full-duplex

**Comment by bstiq** [comment]
Hey,

There was some discussion around this while developing the firmware for rp2040.
For my designs I want to stick to TRS cables.

If you want to add an optional resistor for full duplex / I2C feel free. If it's only optional - and still possible to use TRS / serial, I'll gladly take a PR.

PS please correct me on terminology if necessary, not super familiar.

Regards,

**Comment by bstiq** [comment]
No update for some time
