### ISSUE TITLE
Add hole for blackpill leds

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/adapter-blackpill#7]
At the moment the leds from the blackpill are hidden by the shield pcb.

It might be nice in future updates to add a little hole so they are visible.

Leaving this here for reference.

**Comment by drashna** [comment]
Power LED Being covered is absolutely fine.

For the other LED, this is wired up to C13 (and incorrectly, I might add).  It should be possible to just wire up an LED on the carrier board to make it more visible, if need be.
